import { KocItem } from './types';

// Danh sách 120+ KOC / KOL chuẩn hóa cho hệ thống UpBase B2C
// Bao phủ đầy đủ 4 Tier, 7 Khung lương KL1-KL7, 25 Tệp kênh và các nhãn hàng chủ lực
export const UPBASE_FULL_KOC_MASTER: KocItem[] = [
  // --- TIER 1 & 2: MEGA / MACRO CREATORS (KL6 - KL7, TOP CREATORS) ---
  {
    id: 'koc-1',
    channelId: 'megauriviu',
    channelLink: 'https://www.tiktok.com/@megauriviu',
    stageName: 'Mega Uri Review',
    realName: 'Phạm Ngọc Hiếu An',
    tier: 'TIER_2_MACRO',
    tierLabel: 'Tier 2 (Macro)',
    salaryGrade: 'KL6',
    segment: 'Key Creator',
    tepKenh: 'Review Nữ',
    kocCategory: 'Personal care',
    niche: 'Mỹ phẩm & Review Da Liễu Chuẩn Y Khoa',
    followers: 680000,
    avgViews: 95000,
    rateCardVideo: 15000000,
    bookingFormat: 'Booking Video KOC',
    reliabilityScore: 9.8,
    phone: '0399675534',
    zalo: '0399675534',
    email: 'phamngochieuan@gmail.com',
    shippingAddress: 'Số 18, Ngõ 45 Trần Thái Tông, Cầu Giấy, Hà Nội',
    location: 'Hà Nội',
    cccd: '001201004567',
    bankName: 'Techcombank',
    bankAccount: '1903456789012',
    isOcrVerified: true,
    taxCode: '8549302194',
    gmvBestCase: 350000000,
    recentRevenue: 180000000,
    brandName: 'Royal Ausnz',
    brandApprovalStatus: 'ĐÃ_DUYỆT',
    statusKoc: 'SẴN_SÀNG',
    bookingPic: 'Khánh Vy',
    totalPastDeals: 6,
    historicalRoi: 5.6
  },
  {
    id: 'koc-2',
    channelId: 'chanhbeauty',
    channelLink: 'https://www.tiktok.com/@chanhbeauty',
    stageName: 'Chanh Beauty Review',
    realName: 'Lê Thị Bích Chanh',
    tier: 'TIER_3_MICRO',
    tierLabel: 'Tier 3 (Micro)',
    salaryGrade: 'KL4',
    segment: 'Mid Creator',
    tepKenh: 'Beauty',
    kocCategory: 'Personal care',
    niche: 'Trang Điểm, Skincare & Chăm Sóc Da Nhạy Cảm',
    followers: 125000,
    avgViews: 42000,
    rateCardVideo: 3500000,
    bookingFormat: 'Booking Video KOC',
    reliabilityScore: 9.2,
    phone: '0988776655',
    zalo: '0988776655',
    email: 'bichchanh.beauty@gmail.com',
    shippingAddress: 'Tòa Landmark 2, Vinhomes Central Park, Bình Thạnh, TP.HCM',
    location: 'TP.HCM',
    cccd: '079198003456',
    bankName: 'MB Bank',
    bankAccount: '098877665588',
    isOcrVerified: true,
    taxCode: '8619203810',
    gmvBestCase: 85000000,
    recentRevenue: 48000000,
    brandName: 'Kutieskin',
    brandApprovalStatus: 'ĐÃ_DUYỆT',
    statusKoc: 'SẴN_SÀNG',
    bookingPic: 'Khánh Vy',
    totalPastDeals: 3,
    historicalRoi: 4.2
  },
  {
    id: 'koc-3',
    channelId: 'me_bap_cai',
    channelLink: 'https://www.tiktok.com/@me_bap_cai',
    stageName: 'Mẹ Bắp Cải Chăm Con',
    realName: 'Vũ Thị Hải Yến',
    tier: 'TIER_3_MICRO',
    tierLabel: 'Tier 3 (Micro)',
    salaryGrade: 'KL3',
    segment: 'Mid Creator',
    tepKenh: 'Mẹ bé (bầu)',
    kocCategory: 'Mom and baby',
    niche: 'Chăm Sóc Bé Sơ Sinh & Trẻ Nhỏ, Mẹo Trị Chàm Sữa',
    followers: 86000,
    avgViews: 28000,
    rateCardVideo: 2500000,
    bookingFormat: 'Booking Video KOC',
    reliabilityScore: 8.9,
    phone: '0912345678',
    zalo: '0912345678',
    email: 'haiyen.mebap@gmail.com',
    shippingAddress: 'Số 12A, Ngõ 102 Hoàng Đạo Thúy, Thanh Xuân, Hà Nội',
    location: 'Hà Nội',
    cccd: '026194002341',
    bankName: 'Vietcombank',
    bankAccount: '0011004321987',
    isOcrVerified: true,
    taxCode: '8401928374',
    gmvBestCase: 62000000,
    recentRevenue: 35000000,
    brandName: 'Kutieskin',
    brandApprovalStatus: 'ĐÃ_DUYỆT',
    statusKoc: 'SẴN_SÀNG',
    bookingPic: 'Nguyễn Tuấn Anh',
    totalPastDeals: 5,
    historicalRoi: 3.8
  },
  {
    id: 'koc-4',
    channelId: 'duocsi_thuha',
    channelLink: 'https://www.tiktok.com/@duocsi_thuha',
    stageName: 'Dược Sĩ Thu Hà',
    realName: 'Hoàng Thu Hà',
    tier: 'TIER_2_MACRO',
    tierLabel: 'Tier 2 (Macro)',
    salaryGrade: 'KL5',
    segment: 'Key Creator',
    tepKenh: 'Bác sỹ/chuyên gia',
    kocCategory: 'Personal care',
    niche: 'Dược Sĩ Gia Đình, Tư Vấn Dược Mỹ Phẩm Trẻ Em',
    followers: 320000,
    avgViews: 65000,
    rateCardVideo: 8000000,
    bookingFormat: 'Booking Video KOC',
    reliabilityScore: 9.6,
    phone: '0977889900',
    zalo: '0977889900',
    email: 'duocsithuha.official@gmail.com',
    shippingAddress: 'Nhà Thuốc Thu Hà, 45 Nguyễn Văn Cừ, Long Biên, Hà Nội',
    location: 'Hà Nội',
    cccd: '001192003344',
    bankName: 'VPBank',
    bankAccount: '198723456789',
    isOcrVerified: true,
    taxCode: '8392019485',
    gmvBestCase: 210000000,
    recentRevenue: 120000000,
    brandName: 'Royal Ausnz',
    brandApprovalStatus: 'ĐÃ_DUYỆT',
    statusKoc: 'SẴN_SÀNG',
    bookingPic: 'Nguyễn Tuấn Anh',
    totalPastDeals: 4,
    historicalRoi: 4.9
  },
  {
    id: 'koc-5',
    channelId: 'bacsi_vinh_nhi',
    channelLink: 'https://www.tiktok.com/@bacsi_vinh_nhi',
    stageName: 'BS Nhi Khoa Quang Vinh',
    realName: 'Trần Quang Vinh',
    tier: 'TIER_1_CELEB',
    tierLabel: 'Tier 1 (Celeb/Mega)',
    salaryGrade: 'KL7',
    segment: 'Top Creator',
    tepKenh: 'Bác sỹ/chuyên gia',
    kocCategory: 'Mom and baby',
    niche: 'Bác Sĩ Nhi Khoa Chuyên Khoa I, Dinh Dưỡng & Miễn Dịch',
    followers: 950000,
    avgViews: 180000,
    rateCardVideo: 28000000,
    bookingFormat: 'Booking Video KOC',
    reliabilityScore: 9.9,
    phone: '0903456789',
    zalo: '0903456789',
    email: 'bs.quangvinh.nhi@gmail.com',
    shippingAddress: 'Khoa Nhi BV Quốc Tế, Quận 7, TP.HCM',
    location: 'TP.HCM',
    cccd: '079085001234',
    bankName: 'Vietcombank',
    bankAccount: '0071009876543',
    isOcrVerified: true,
    taxCode: '8129384756',
    gmvBestCase: 680000000,
    recentRevenue: 420000000,
    brandName: 'Royal Ausnz',
    brandApprovalStatus: 'ĐÃ_DUYỆT',
    statusKoc: 'SẴN_SÀNG',
    bookingPic: 'Nguyễn Tuấn Anh',
    totalPastDeals: 7,
    historicalRoi: 6.2
  },
  {
    id: 'koc-6',
    channelId: 'linh_kem_review',
    channelLink: 'https://www.tiktok.com/@linh_kem_review',
    stageName: 'Linh Kem Daily',
    realName: 'Nguyễn Thùy Linh',
    tier: 'TIER_4_AFFILIATE',
    tierLabel: 'Tier 4 (Nano)',
    salaryGrade: 'KL2',
    segment: 'Massive Creator',
    tepKenh: 'Review Nữ',
    kocCategory: 'Personal care',
    niche: 'Review Đồ Tiện Ích, Mỹ Phẩm Học Sinh Sinh Viên',
    followers: 35000,
    avgViews: 15000,
    rateCardVideo: 1200000,
    bookingFormat: 'Booking Video KOC',
    reliabilityScore: 8.5,
    phone: '0934567890',
    zalo: '0934567890',
    email: 'linhkem.daily@gmail.com',
    shippingAddress: 'Ký Túc Xá ĐH Kinh Tế Quốc Dân, Giải Phóng, Hà Nội',
    location: 'Hà Nội',
    cccd: '038302005678',
    bankName: 'Techcombank',
    bankAccount: '190382910293',
    isOcrVerified: false,
    taxCode: 'Chưa có',
    gmvBestCase: 25000000,
    recentRevenue: 12000000,
    brandName: 'pHCare',
    brandApprovalStatus: 'CHỜ_DUYỆT',
    statusKoc: 'SẴN_SÀNG',
    bookingPic: 'Nguyễn Thu Trang',
    totalPastDeals: 2,
    historicalRoi: 2.9
  },
  {
    id: 'koc-7',
    channelId: 'goc_nha_bong',
    channelLink: 'https://www.tiktok.com/@goc_nha_bong',
    stageName: 'Góc Nhà Bống (Mẹ Bỉm)',
    realName: 'Đặng Thanh Thảo',
    tier: 'TIER_4_AFFILIATE',
    tierLabel: 'Tier 4 (Nano)',
    salaryGrade: 'KL1',
    segment: 'Massive Creator',
    tepKenh: 'Mẹ bé (bầu)',
    kocCategory: 'Mom and baby',
    niche: 'Đời Sống Mẹ Bỉm, Review Tã Bỉm & Kem Bôi Da',
    followers: 18000,
    avgViews: 8500,
    rateCardVideo: 800000,
    bookingFormat: 'Booking Video KOC',
    reliabilityScore: 8.7,
    phone: '0966554433',
    zalo: '0966554433',
    email: 'gocnhabong@gmail.com',
    shippingAddress: 'Số 5, Ngách 20/4 Quan Nhân, Thanh Xuân, Hà Nội',
    location: 'Hà Nội',
    cccd: '001198007890',
    bankName: 'TPBank',
    bankAccount: '03984729101',
    isOcrVerified: true,
    taxCode: '8594039281',
    gmvBestCase: 18000000,
    recentRevenue: 9500000,
    brandName: 'Kutieskin',
    brandApprovalStatus: 'ĐÃ_DUYỆT',
    statusKoc: 'SẴN_SÀNG',
    bookingPic: 'Khánh Vy',
    totalPastDeals: 3,
    historicalRoi: 3.1
  },
  {
    id: 'koc-8',
    channelId: 'drnguyendalieu',
    channelLink: 'https://www.tiktok.com/@drnguyendalieu',
    stageName: 'Bác Sĩ Da Liễu Nguyên',
    realName: 'Nguyễn Văn Nguyên',
    tier: 'TIER_3_MICRO',
    tierLabel: 'Tier 3 (Micro)',
    salaryGrade: 'KL4',
    segment: 'Mid Creator',
    tepKenh: 'Bác sỹ/chuyên gia',
    kocCategory: 'Personal care',
    niche: 'Khám & Kê Đơn Da Liễu, Phục Hồi Da Hư Tổn',
    followers: 185000,
    avgViews: 52000,
    rateCardVideo: 4500000,
    bookingFormat: 'Booking Video KOC',
    reliabilityScore: 9.9,
    phone: '0918273645',
    zalo: '0918273645',
    email: 'drnguyen.dalieu@gmail.com',
    shippingAddress: 'Phòng Khám Da Liễu Dr. Nguyên, Đường 3/2, Quận 10, TP.HCM',
    location: 'TP.HCM',
    cccd: '001092837461',
    bankName: 'VietinBank',
    bankAccount: '1029384756',
    isOcrVerified: true,
    taxCode: '8302918475',
    gmvBestCase: 120000000,
    recentRevenue: 82000000,
    brandName: 'pHCare',
    brandApprovalStatus: 'CHỜ_DUYỆT',
    statusKoc: 'SẴN_SÀNG',
    bookingPic: 'Lê Thị Thùy Linh',
    totalPastDeals: 4,
    historicalRoi: 4.8
  },

  // --- KOC 9 ĐẾN 20: TẬP TRUNG NGÀNH HÀNG MẸ & BÉ, DA LIỄU NHẠY CẢM ---
  {
    id: 'koc-9',
    channelId: 'me_dau_tay',
    channelLink: 'https://www.tiktok.com/@me_dau_tay',
    stageName: 'Mẹ Dâu Tây Nuôi Con',
    realName: 'Phan Diệu Linh',
    tier: 'TIER_3_MICRO',
    tierLabel: 'Tier 3 (Micro)',
    salaryGrade: 'KL3',
    segment: 'Mid Creator',
    tepKenh: 'Mẹ bé (bầu)',
    kocCategory: 'Mom and baby',
    niche: 'Chăm sóc trẻ sơ sinh, dinh dưỡng ăn dặm & đồ chơi thông minh',
    followers: 94000,
    avgViews: 31000,
    rateCardVideo: 2800000,
    bookingFormat: 'Booking Video KOC',
    reliabilityScore: 9.1,
    phone: '0943219876',
    zalo: '0943219876',
    email: 'medautay@gmail.com',
    shippingAddress: 'Khu Đô Thị Ecopark, Văn Giang, Hưng Yên',
    location: 'Hưng Yên',
    cccd: '033195004561',
    bankName: 'Vietcombank',
    bankAccount: '0451000392817',
    isOcrVerified: true,
    taxCode: '8649201948',
    gmvBestCase: 54000000,
    recentRevenue: 28000000,
    brandName: 'Kutieskin',
    brandApprovalStatus: 'ĐÃ_DUYỆT',
    statusKoc: 'SẴN_SÀNG',
    bookingPic: 'Khánh Vy',
    totalPastDeals: 3,
    historicalRoi: 3.9
  },
  {
    id: 'koc-10',
    channelId: 'duocsi_mai_anh',
    channelLink: 'https://www.tiktok.com/@duocsi_mai_anh',
    stageName: 'Dược Sĩ Mai Anh Official',
    realName: 'Lê Mai Anh',
    tier: 'TIER_2_MACRO',
    tierLabel: 'Tier 2 (Macro)',
    salaryGrade: 'KL5',
    segment: 'Key Creator',
    tepKenh: 'Bác sỹ/chuyên gia',
    kocCategory: 'Personal care',
    niche: 'Dược sĩ tư vấn kháng sinh, kem bôi da liễu & tăng đề kháng',
    followers: 275000,
    avgViews: 58000,
    rateCardVideo: 7500000,
    bookingFormat: 'Booking Video KOC',
    reliabilityScore: 9.7,
    phone: '0971234567',
    zalo: '0971234567',
    email: 'maianh.pharmacy@gmail.com',
    shippingAddress: '158 Bạch Mai, Hai Bà Trưng, Hà Nội',
    location: 'Hà Nội',
    cccd: '001193006789',
    bankName: 'Techcombank',
    bankAccount: '190367281920',
    isOcrVerified: true,
    taxCode: '8573920194',
    gmvBestCase: 195000000,
    recentRevenue: 110000000,
    brandName: 'Royal Ausnz',
    brandApprovalStatus: 'ĐÃ_DUYỆT',
    statusKoc: 'SẴN_SÀNG',
    bookingPic: 'Nguyễn Tuấn Anh',
    totalPastDeals: 5,
    historicalRoi: 5.1
  },
  {
    id: 'koc-11',
    channelId: 'nhatha_beauty',
    channelLink: 'https://www.tiktok.com/@nhatha_beauty',
    stageName: 'Nhật Hạ Skincare',
    realName: 'Đỗ Nhật Hạ',
    tier: 'TIER_3_MICRO',
    tierLabel: 'Tier 3 (Micro)',
    salaryGrade: 'KL4',
    segment: 'Mid Creator',
    tepKenh: 'Beauty',
    kocCategory: 'Personal care',
    niche: 'Skincare khoa học, phân tích thành phần & kem chống nắng',
    followers: 142000,
    avgViews: 46000,
    rateCardVideo: 4000000,
    bookingFormat: 'Booking Video KOC',
    reliabilityScore: 9.3,
    phone: '0981928374',
    zalo: '0981928374',
    email: 'nhatha.beauty@gmail.com',
    shippingAddress: 'Chung cư Vinhomes Smart City, Nam Từ Liêm, Hà Nội',
    location: 'Hà Nội',
    cccd: '001197003829',
    bankName: 'MB Bank',
    bankAccount: '098192837400',
    isOcrVerified: true,
    taxCode: '8493029184',
    gmvBestCase: 92000000,
    recentRevenue: 51000000,
    brandName: 'La Roche-Posay',
    brandApprovalStatus: 'ĐÃ_DUYỆT',
    statusKoc: 'SẴN_SÀNG',
    bookingPic: 'Khánh Vy',
    totalPastDeals: 4,
    historicalRoi: 4.4
  },
  {
    id: 'koc-12',
    channelId: 'me_sam_daily',
    channelLink: 'https://www.tiktok.com/@me_sam_daily',
    stageName: 'Mẹ Sữa và Sâm',
    realName: 'Nguyễn Thị Hồng Sâm',
    tier: 'TIER_4_AFFILIATE',
    tierLabel: 'Tier 4 (Nano)',
    salaryGrade: 'KL2',
    segment: 'Massive Creator',
    tepKenh: 'Mẹ bé (bầu)',
    kocCategory: 'Mom and baby',
    niche: 'Chăm sóc mẹ sau sinh, sữa non & phòng hăm tã cho bé',
    followers: 41000,
    avgViews: 17000,
    rateCardVideo: 1500000,
    bookingFormat: 'Booking Video KOC',
    reliabilityScore: 8.8,
    phone: '0962345678',
    zalo: '0962345678',
    email: 'mesam.daily@gmail.com',
    shippingAddress: 'Số 42, Phố Huế, Hoàn Kiếm, Hà Nội',
    location: 'Hà Nội',
    cccd: '001196001294',
    bankName: 'Agribank',
    bankAccount: '1400205492817',
    isOcrVerified: true,
    taxCode: '8392019482',
    gmvBestCase: 28000000,
    recentRevenue: 14000000,
    brandName: 'Kutieskin',
    brandApprovalStatus: 'ĐÃ_DUYỆT',
    statusKoc: 'SẴN_SÀNG',
    bookingPic: 'Khánh Vy',
    totalPastDeals: 2,
    historicalRoi: 3.2
  },
  {
    id: 'koc-13',
    channelId: 'dr_le_phuc',
    channelLink: 'https://www.tiktok.com/@dr_le_phuc',
    stageName: 'ThS.BS Lê Hồng Phúc',
    realName: 'Lê Hồng Phúc',
    tier: 'TIER_2_MACRO',
    tierLabel: 'Tier 2 (Macro)',
    salaryGrade: 'KL6',
    segment: 'Key Creator',
    tepKenh: 'Bác sỹ/chuyên gia',
    kocCategory: 'Personal care',
    niche: 'Thạc sĩ Bác sĩ Da Liễu TW, điều trị viêm da cơ địa',
    followers: 410000,
    avgViews: 82000,
    rateCardVideo: 12000000,
    bookingFormat: 'Booking Video KOC',
    reliabilityScore: 9.8,
    phone: '0909182736',
    zalo: '0909182736',
    email: 'dr.phuc.dalieu@gmail.com',
    shippingAddress: 'Phòng khám Da Liễu Dr. Phúc, Đống Đa, Hà Nội',
    location: 'Hà Nội',
    cccd: '001089004562',
    bankName: 'BIDV',
    bankAccount: '21510003928172',
    isOcrVerified: true,
    taxCode: '8201928374',
    gmvBestCase: 290000000,
    recentRevenue: 165000000,
    brandName: 'Kutieskin',
    brandApprovalStatus: 'ĐÃ_DUYỆT',
    statusKoc: 'SẴN_SÀNG',
    bookingPic: 'Nguyễn Tuấn Anh',
    totalPastDeals: 6,
    historicalRoi: 5.4
  },
  {
    id: 'koc-14',
    channelId: 'huyen_be_map',
    channelLink: 'https://www.tiktok.com/@huyen_be_map',
    stageName: 'Huyền Bé Mập Review',
    realName: 'Vũ Thị Thanh Huyền',
    tier: 'TIER_4_AFFILIATE',
    tierLabel: 'Tier 4 (Nano)',
    salaryGrade: 'KL1',
    segment: 'Massive Creator',
    tepKenh: 'Review Nữ',
    kocCategory: 'Reviewer',
    niche: 'Đồ dùng học sinh, son dưỡng & sữa tắm bình dân',
    followers: 22000,
    avgViews: 9200,
    rateCardVideo: 900000,
    bookingFormat: 'Booking Video KOC',
    reliabilityScore: 8.6,
    phone: '0938472918',
    zalo: '0938472918',
    email: 'huyenbemap@gmail.com',
    shippingAddress: '234 Điện Biên Phủ, Phường 15, Bình Thạnh, TP.HCM',
    location: 'TP.HCM',
    cccd: '079301004829',
    bankName: 'VPBank',
    bankAccount: '0938472918',
    isOcrVerified: false,
    taxCode: 'Chưa có',
    gmvBestCase: 19000000,
    recentRevenue: 8500000,
    brandName: 'pHCare',
    brandApprovalStatus: 'CHỜ_DUYỆT',
    statusKoc: 'SẴN_SÀNG',
    bookingPic: 'Nguyễn Thu Trang',
    totalPastDeals: 1,
    historicalRoi: 2.8
  },
  {
    id: 'koc-15',
    channelId: 'me_gau_cham_con',
    channelLink: 'https://www.tiktok.com/@me_gau_cham_con',
    stageName: 'Mẹ Gấu Nuôi Con Khoa Học',
    realName: 'Bùi Lan Phương',
    tier: 'TIER_3_MICRO',
    tierLabel: 'Tier 3 (Micro)',
    salaryGrade: 'KL3',
    segment: 'Mid Creator',
    tepKenh: 'Mẹ bé (bầu)',
    kocCategory: 'Mom and baby',
    niche: 'Tắm bé sơ sinh, massage chống đầy hơi & kem nẻ mùa đông',
    followers: 78000,
    avgViews: 26000,
    rateCardVideo: 2400000,
    bookingFormat: 'Booking Video KOC',
    reliabilityScore: 9.0,
    phone: '0976543210',
    zalo: '0976543210',
    email: 'megau.nuoicon@gmail.com',
    shippingAddress: 'Số 19 Lê Văn Lương, Nhân Chính, Thanh Xuân, Hà Nội',
    location: 'Hà Nội',
    cccd: '001194008291',
    bankName: 'Techcombank',
    bankAccount: '190349281726',
    isOcrVerified: true,
    taxCode: '8501928371',
    gmvBestCase: 58000000,
    recentRevenue: 31000000,
    brandName: 'Kutieskin',
    brandApprovalStatus: 'ĐÃ_DUYỆT',
    statusKoc: 'SẴN_SÀNG',
    bookingPic: 'Khánh Vy',
    totalPastDeals: 4,
    historicalRoi: 3.7
  },
  {
    id: 'koc-16',
    channelId: 'trang_skin_lab',
    channelLink: 'https://www.tiktok.com/@trang_skin_lab',
    stageName: 'Trang Skin Lab',
    realName: 'Nguyễn Huyền Trang',
    tier: 'TIER_3_MICRO',
    tierLabel: 'Tier 3 (Micro)',
    salaryGrade: 'KL4',
    segment: 'Mid Creator',
    tepKenh: 'Beauty',
    kocCategory: 'Personal care',
    niche: 'Chăm sóc da dầu mụn, phục hồi B5 & tẩy tế bào chết hóa học',
    followers: 115000,
    avgViews: 38000,
    rateCardVideo: 3200000,
    bookingFormat: 'Booking Video KOC',
    reliabilityScore: 9.2,
    phone: '0919283746',
    zalo: '0919283746',
    email: 'trangskinlab@gmail.com',
    shippingAddress: 'Khu dân cư Him Lam, Quận 7, TP.HCM',
    location: 'TP.HCM',
    cccd: '079196003928',
    bankName: 'Vietcombank',
    bankAccount: '0071004928172',
    isOcrVerified: true,
    taxCode: '8492019483',
    gmvBestCase: 76000000,
    recentRevenue: 42000000,
    brandName: 'La Roche-Posay',
    brandApprovalStatus: 'ĐÃ_DUYỆT',
    statusKoc: 'SẴN_SÀNG',
    bookingPic: 'Khánh Vy',
    totalPastDeals: 3,
    historicalRoi: 4.1
  },
  {
    id: 'koc-17',
    channelId: 'co_giao_thao_baby',
    channelLink: 'https://www.tiktok.com/@co_giao_thao_baby',
    stageName: 'Cô Giáo Thảo Mầm Non',
    realName: 'Hoàng Phương Thảo',
    tier: 'TIER_4_AFFILIATE',
    tierLabel: 'Tier 4 (Nano)',
    salaryGrade: 'KL2',
    segment: 'Massive Creator',
    tepKenh: 'Mẹ bé (bầu)',
    kocCategory: 'Mom and baby',
    niche: 'Giáo viên mầm non chia sẻ cách chăm sóc da và bệnh hô hấp ở trẻ',
    followers: 38000,
    avgViews: 14000,
    rateCardVideo: 1300000,
    bookingFormat: 'Booking Video KOC',
    reliabilityScore: 8.9,
    phone: '0948291029',
    zalo: '0948291029',
    email: 'cogiaothao.mamnon@gmail.com',
    shippingAddress: 'Trường Mầm Non Ánh Dương, Cầu Giấy, Hà Nội',
    location: 'Hà Nội',
    cccd: '001195009182',
    bankName: 'Techcombank',
    bankAccount: '190392817261',
    isOcrVerified: true,
    taxCode: '8392019481',
    gmvBestCase: 24000000,
    recentRevenue: 13500000,
    brandName: 'Kutieskin',
    brandApprovalStatus: 'ĐÃ_DUYỆT',
    statusKoc: 'SẴN_SÀNG',
    bookingPic: 'Lê Thị Thùy Linh',
    totalPastDeals: 2,
    historicalRoi: 3.4
  },
  {
    id: 'koc-18',
    channelId: 'bs_kim_ngan',
    channelLink: 'https://www.tiktok.com/@bs_kim_ngan',
    stageName: 'BS Dinh Dưỡng Kim Ngân',
    realName: 'Nguyễn Thị Kim Ngân',
    tier: 'TIER_2_MACRO',
    tierLabel: 'Tier 2 (Macro)',
    salaryGrade: 'KL5',
    segment: 'Key Creator',
    tepKenh: 'Bác sỹ/chuyên gia',
    kocCategory: 'Mom and baby',
    niche: 'Bác sĩ Viện Dinh Dưỡng, tư vấn sữa công thức & canxi chiều cao',
    followers: 240000,
    avgViews: 54000,
    rateCardVideo: 7000000,
    bookingFormat: 'Booking Video KOC',
    reliabilityScore: 9.7,
    phone: '0912938475',
    zalo: '0912938475',
    email: 'bs.kimngan.dinhduong@gmail.com',
    shippingAddress: 'Viện Dinh Dưỡng Quốc Gia, 48B Tăng Bạt Hổ, Hà Nội',
    location: 'Hà Nội',
    cccd: '001091004829',
    bankName: 'VietinBank',
    bankAccount: '10382910482',
    isOcrVerified: true,
    taxCode: '8291029485',
    gmvBestCase: 180000000,
    recentRevenue: 98000000,
    brandName: 'Royal Ausnz',
    brandApprovalStatus: 'ĐÃ_DUYỆT',
    statusKoc: 'SẴN_SÀNG',
    bookingPic: 'Nguyễn Tuấn Anh',
    totalPastDeals: 5,
    historicalRoi: 4.9
  },
  {
    id: 'koc-19',
    channelId: 'nhung_me_ken',
    channelLink: 'https://www.tiktok.com/@nhung_me_ken',
    stageName: 'Mẹ Kén & Bống',
    realName: 'Trịnh Thị Cẩm Nhung',
    tier: 'TIER_4_AFFILIATE',
    tierLabel: 'Tier 4 (Nano)',
    salaryGrade: 'KL1',
    segment: 'Massive Creator',
    tepKenh: 'Mẹ bé (bầu)',
    kocCategory: 'Mom and baby',
    niche: 'Nhật ký bỉm sữa 2 bé, kem bôi muỗi đốt & xịt họng thảo dược',
    followers: 19500,
    avgViews: 7800,
    rateCardVideo: 850000,
    bookingFormat: 'Booking Video KOC',
    reliabilityScore: 8.7,
    phone: '0978192837',
    zalo: '0978192837',
    email: 'meken.bong@gmail.com',
    shippingAddress: 'Thôn Đông Trạch, Ngũ Hiệp, Thanh Trì, Hà Nội',
    location: 'Hà Nội',
    cccd: '001199003829',
    bankName: 'MB Bank',
    bankAccount: '0978192837',
    isOcrVerified: true,
    taxCode: '8583920194',
    gmvBestCase: 16000000,
    recentRevenue: 8200000,
    brandName: 'Kutieskin',
    brandApprovalStatus: 'ĐÃ_DUYỆT',
    statusKoc: 'SẴN_SÀNG',
    bookingPic: 'Khánh Vy',
    totalPastDeals: 3,
    historicalRoi: 3.0
  },
  {
    id: 'koc-20',
    channelId: 'an_nhien_beauty',
    channelLink: 'https://www.tiktok.com/@an_nhien_beauty',
    stageName: 'An Nhiên Skincare Routine',
    realName: 'Trần An Nhiên',
    tier: 'TIER_3_MICRO',
    tierLabel: 'Tier 3 (Micro)',
    salaryGrade: 'KL3',
    segment: 'Mid Creator',
    tepKenh: 'Beauty',
    kocCategory: 'Personal care',
    niche: 'Chăm sóc da tuổi 25+, chống lão hóa, phục hồi màng bảo vệ da',
    followers: 89000,
    avgViews: 29000,
    rateCardVideo: 2600000,
    bookingFormat: 'Booking Video KOC',
    reliabilityScore: 9.0,
    phone: '0937482910',
    zalo: '0937482910',
    email: 'annhien.beauty@gmail.com',
    shippingAddress: 'Căn hộ Riverpark Premier, Phú Mỹ Hưng, Quận 7, TP.HCM',
    location: 'TP.HCM',
    cccd: '079195004829',
    bankName: 'Techcombank',
    bankAccount: '190384729182',
    isOcrVerified: true,
    taxCode: '8492019472',
    gmvBestCase: 65000000,
    recentRevenue: 34000000,
    brandName: 'Senka',
    brandApprovalStatus: 'ĐÃ_DUYỆT',
    statusKoc: 'SẴN_SÀNG',
    bookingPic: 'Khánh Vy',
    totalPastDeals: 3,
    historicalRoi: 3.8
  },

  // --- HÀNG LOẠT KOC ĐA DẠNG CÁC TỈNH THÀNH, ĐỦ TIER VÀ KHUNG LƯƠNG TỪ 21 ĐẾN 120 ---
  ...generateExtendedKocs(21, 125)
];

// Hàm sinh danh bạ hàng trăm KOC chuẩn hóa
function generateExtendedKocs(startIdx: number, endIdx: number): KocItem[] {
  const result: KocItem[] = [];

  const firstNames = ['Nguyễn', 'Trần', 'Lê', 'Phạm', 'Hoàng', 'Vũ', 'Đặng', 'Bùi', 'Đỗ', 'Hồ', 'Ngô', 'Dương', 'Lý'];
  const middleFemales = ['Thị', 'Thanh', 'Ngọc', 'Phương', 'Mai', 'Thùy', 'Hồng', 'Bích', 'Quỳnh', 'Thu', 'Diệu'];
  const lastFemales = ['Linh', 'Trang', 'Hương', 'Hà', 'Anh', 'Chi', 'Yến', 'My', 'Vy', 'Nhi', 'Ngân', 'Thảo', 'Trâm', 'Chanh', 'Duyên'];

  const niches = [
    { niche: 'Mẹ Bỉm Nuôi Con, Trị Hăm & Dị Ứng Da Cho Bé', tep: 'Mẹ bé (bầu)' as const, cat: 'Mom and baby' as const, brand: 'Kutieskin' },
    { niche: 'Dược Sĩ Da Liễu Khuyên Dùng Cho Trẻ Nhỏ', tep: 'Bác sỹ/chuyên gia' as const, cat: 'Mom and baby' as const, brand: 'Kutieskin' },
    { niche: 'Bác Sĩ Dinh Dưỡng, Sữa Hoàng Gia Tăng Cân Cao Lớn', tep: 'Bác sỹ/chuyên gia' as const, cat: 'Mom and baby' as const, brand: 'Royal Ausnz' },
    { niche: 'Skincare Nhẹ Dịu Cho Da Nhạy Cảm & treatment', tep: 'Beauty' as const, cat: 'Personal care' as const, brand: 'La Roche-Posay' },
    { niche: 'Review Mỹ Phẩm Sinh Viên & Nước Tẩy Trang', tep: 'Review Nữ' as const, cat: 'Personal care' as const, brand: 'Senka' },
    { niche: 'Chăm Sóc Vệ Sinh Phụ Nữ & Sức Khỏe Gia Đình', tep: 'Review Nữ' as const, cat: 'Personal care' as const, brand: 'pHCare' },
    { niche: 'Review Đồ Mẹ Bé Đời Thực, Chia Sẻ Kinh Nghiệm Bầu', tep: 'Mẹ bé (bầu)' as const, cat: 'Mom and baby' as const, brand: 'Kutieskin' },
    { niche: 'Dưỡng Ẩm Chống Nẻ & Phục Hồi Chàm Sữa Sơ Sinh', tep: 'Mẹ bé (bầu)' as const, cat: 'Mom and baby' as const, brand: 'Kutieskin' },
    { niche: 'Beauty Blogger Test Kem Chống Nắng Thực Tế', tep: 'Beauty' as const, cat: 'Personal care' as const, brand: 'Mega Uri' },
    { niche: 'Bác Sĩ Nhi Khoa Hướng Dẫn Tăng Sức Đề Kháng', tep: 'Bác sỹ/chuyên gia' as const, cat: 'Mom and baby' as const, brand: 'Royal Ausnz' }
  ];

  const pics = ['Khánh Vy', 'Nguyễn Tuấn Anh', 'Lê Thị Thùy Linh', 'Nguyễn Anh', 'Nguyễn Thu Trang'];
  const locations = ['Hà Nội', 'TP.HCM', 'Đà Nẵng', 'Hải Phòng', 'Cần Thơ', 'Bình Dương', 'Đồng Nai', 'Nghệ An'];
  const banks = ['Vietcombank', 'Techcombank', 'MB Bank', 'VPBank', 'BIDV', 'VietinBank', 'TPBank', 'ACB'];

  for (let i = startIdx; i <= endIdx; i++) {
    const fn = firstNames[i % firstNames.length];
    const mn = middleFemales[i % middleFemales.length];
    const ln = lastFemales[i % lastFemales.length];
    const realName = `${fn} ${mn} ${ln}`;
    
    const nicheObj = niches[i % niches.length];
    const stagePrefix = nicheObj.tep === 'Bác sỹ/chuyên gia' ? 'BS.' : (nicheObj.tep === 'Mẹ bé (bầu)' ? 'Mẹ ' : '');
    const stageName = `${stagePrefix}${ln} ${nicheObj.tep === 'Mẹ bé (bầu)' ? 'Chăm Con' : (nicheObj.tep === 'Beauty' ? 'Beauty' : 'Daily')} (KOC #${i})`;
    const channelId = `${ln.toLowerCase()}_${i}_upbase`;
    const pic = pics[i % pics.length];
    const loc = locations[i % locations.length];
    const bank = banks[i % banks.length];

    // Determine Tier & Salary Grade
    let tier: KocItem['tier'] = 'TIER_4_AFFILIATE';
    let tierLabel = 'Tier 4 (Nano)';
    let salaryGrade: KocItem['salaryGrade'] = 'KL2';
    let segment: KocItem['segment'] = 'Massive Creator';
    let followers = 15000 + (i * 3500) % 95000;
    let avgViews = Math.round(followers * 0.35);
    let rateCard = 1200000;

    if (i % 12 === 0) {
      tier = 'TIER_2_MACRO';
      tierLabel = 'Tier 2 (Macro)';
      salaryGrade = 'KL6';
      segment = 'Key Creator';
      followers = 280000 + (i * 7000) % 350000;
      avgViews = Math.round(followers * 0.28);
      rateCard = 12000000 + (i % 5) * 1500000;
    } else if (i % 6 === 0) {
      tier = 'TIER_3_MICRO';
      tierLabel = 'Tier 3 (Micro)';
      salaryGrade = 'KL4';
      segment = 'Mid Creator';
      followers = 85000 + (i * 4000) % 95000;
      avgViews = Math.round(followers * 0.32);
      rateCard = 3500000 + (i % 4) * 800000;
    } else if (i % 4 === 0) {
      tier = 'TIER_3_MICRO';
      tierLabel = 'Tier 3 (Micro)';
      salaryGrade = 'KL3';
      segment = 'Mid Creator';
      followers = 50000 + (i * 3000) % 40000;
      avgViews = Math.round(followers * 0.3);
      rateCard = 2200000 + (i % 3) * 500000;
    } else if (i % 3 === 0) {
      tier = 'TIER_4_AFFILIATE';
      tierLabel = 'Tier 4 (Nano)';
      salaryGrade = 'KL1';
      segment = 'Massive Creator';
      followers = 12000 + (i * 1200) % 25000;
      avgViews = Math.round(followers * 0.4);
      rateCard = 800000 + (i % 2) * 200000;
    }

    const isVerified = (i % 5 !== 0); // 80% KOC đã OCR xác minh
    const cccd = isVerified ? `0${(10000000000 + i * 837461) % 90000000000}` : 'Chưa có';
    const taxCode = isVerified ? `8${(100000000 + i * 39281) % 900000000}` : 'Chưa có';

    result.push({
      id: `koc-${i}`,
      channelId,
      channelLink: `https://www.tiktok.com/@${channelId}`,
      stageName,
      realName,
      tier,
      tierLabel,
      salaryGrade,
      segment,
      tepKenh: nicheObj.tep,
      kocCategory: nicheObj.cat,
      niche: nicheObj.niche,
      followers,
      avgViews,
      rateCardVideo: rateCard,
      bookingFormat: 'Booking Video KOC',
      reliabilityScore: +(8.5 + ((i % 15) * 0.1)).toFixed(1),
      phone: `09${String(10000000 + i * 7391).slice(0, 8)}`,
      zalo: `09${String(10000000 + i * 7391).slice(0, 8)}`,
      email: `${channelId}@gmail.com`,
      shippingAddress: `Số ${i * 3}, Đường ${i % 2 === 0 ? 'Giải Phóng' : 'Cộng Hòa'}, ${loc}`,
      location: loc,
      cccd,
      bankName: bank,
      bankAccount: `${String(1000000000 + i * 92831)}`,
      isOcrVerified: isVerified,
      taxCode,
      gmvBestCase: Math.round(rateCard * (8 + (i % 12))),
      recentRevenue: Math.round(rateCard * (4 + (i % 8))),
      brandName: nicheObj.brand,
      brandApprovalStatus: (i % 7 === 0) ? 'CHỜ_DUYỆT' : 'ĐÃ_DUYỆT',
      statusKoc: (i % 10 === 0) ? 'ĐANG_LIÊN_HỆ' : 'SẴN_SÀNG',
      bookingPic: pic,
      totalPastDeals: (i % 6) + 1,
      historicalRoi: +(2.5 + (i % 35) * 0.1).toFixed(1)
    });
  }

  return result;
}
